# Generated by Django 5.1.2 on 2024-10-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValleAIReservations', '0003_table_delete_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('c', 'Confirmada'), ('e', 'Espera')], default='espera', max_length=10),
        ),
        migrations.CreateModel(
            name='BookedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValleAIReservations.reserva')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValleAIReservations.table')),
            ],
        ),
    ]
