# Generated by Django 5.1.2 on 2024-10-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValleAIReservations', '0004_reserva_status_bookedtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='waitlist_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
