# Generated by Django 5.1.2 on 2024-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValleAIReservations', '0005_reserva_waitlist_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtable',
            name='end_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
