# Generated by Django 5.1.2 on 2024-10-20 13:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValleAIReservations', '0006_alter_bookedtable_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtable',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
